services:
  - type: web
    name: upi-cryptoconnect-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install --production --legacy-peer-deps
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 1000
      - key: NODE_VERSION
        value: 18.19.0
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CURRENCY_API_KEY
        sync: false
      - key: CRYPTO_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
